
export default function handler(req, res) {
    res.status(200).json(
        [
            { country: "China", region: "Asia" },
            { country: "India", region: "Asia" },
            { country: "United States", region: "North America" },
            { country: "Indonesia", region: "Asia" },
            { country: "Pakistan", region: "Asia" },
            { country: "Brazil", region: "Latin America" },
            { country: "Nigeria", region: "Africa" },
            { country: "Bangladesh", region: "Asia" },
            { country: "Russia", region: "Europe" },
            { country: "Mexico", region: "Latin America" },
            { country: "Japan", region: "Asia" },
            { country: "Ethiopia", region: "Africa" },
            { country: "Philippines", region: "Asia" },
            { country: "Egypt", region: "Africa" },
            { country: "Vietnam", region: "Asia" },
            { country: "DR Congo", region: "Africa" },
            { country: "Turkey", region: "Asia" },
            { country: "Iran", region: "Asia" },
            { country: "Germany", region: "Europe" },
            { country: "Thailand", region: "Asia" },
            { country: "United Kingdom", region: "Europe" },
            { country: "France", region: "Europe" },
            { country: "Italy", region: "Europe" },
            { country: "Tanzania", region: "Africa" },
            { country: "South Africa", region: "Africa" },
            { country: "Myanmar", region: "Asia" },
            { country: "Kenya", region: "Africa" },
            { country: "South Korea", region: "Asia" },
            { country: "Colombia", region: "Latin America" },
            { country: "Spain", region: "Europe" },
            { country: "Uganda", region: "Africa" },
            { country: "Argentina", region: "Latin America" },
            { country: "Algeria", region: "Africa" },
            { country: "Sudan", region: "Africa" },
            { country: "Ukraine", region: "Europe" },
            { country: "Iraq", region: "Asia" },
            { country: "Afghanistan", region: "Asia" },
            { country: "Poland", region: "Europe" },
            { country: "Canada", region: "North America" },
            { country: "Morocco", region: "Africa" },
            { country: "Saudi Arabia", region: "Asia" },
            { country: "Uzbekistan", region: "Asia" },
            { country: "Peru", region: "Latin America" },
            { country: "Angola", region: "Africa" },
            { country: "Malaysia", region: "Asia" },
            { country: "Mozambique", region: "Africa" },
            { country: "Ghana", region: "Africa" },
            { country: "Yemen", region: "Asia" },
            { country: "Nepal", region: "Asia" },
            { country: "Venezuela", region: "Latin America" },
            { country: "Madagascar", region: "Africa" },
            { country: "Cameroon", region: "Africa" },
            { country: "Côte d'Ivoire", region: "Africa" },
            { country: "North Korea", region: "Asia" },
            { country: "Australia", region: "Oceania" },
            { country: "Niger", region: "Africa" },
            { country: "Sri Lanka", region: "Asia" },
            { country: "Burkina Faso", region: "Africa" },
            { country: "Mali", region: "Africa" },
            { country: "Romania", region: "Europe" },
            { country: "Malawi", region: "Africa" },
            { country: "Chile", region: "Latin America" },
            { country: "Kazakhstan", region: "Asia" },
            { country: "Zambia", region: "Africa" },
            { country: "Guatemala", region: "Latin America" },
            { country: "Ecuador", region: "Latin America" },
            { country: "Syria", region: "Asia" },
            { country: "Netherlands", region: "Europe" },
            { country: "Senegal", region: "Africa" },
            { country: "Cambodia", region: "Asia" },
            { country: "Chad", region: "Africa" },
            { country: "Somalia", region: "Africa" },
            { country: "Zimbabwe", region: "Africa" },
            { country: "Guinea", region: "Africa" },
            { country: "Rwanda", region: "Africa" },
            { country: "Benin", region: "Africa" },
            { country: "Burundi", region: "Africa" },
            { country: "Tunisia", region: "Africa" },
            { country: "Bolivia", region: "Latin America" },
            { country: "Belgium", region: "Europe" },
            { country: "Haiti", region: "Latin America" },
            { country: "Cuba", region: "Latin America" },
            { country: "South Sudan", region: "Africa" },
            { country: "Dominican Republic", region: "Latin America" },
            { country: "Czech Republic (Czechia)", region: "Europe" },
            { country: "Greece", region: "Europe" },
            { country: "Jordan", region: "Asia" },
            { country: "Portugal", region: "Europe" },
            { country: "Azerbaijan", region: "Asia" },
            { country: "Sweden", region: "Europe" },
            { country: "Honduras", region: "Latin America" },
            { country: "United Arab Emirates", region: "Asia" },
            { country: "Hungary", region: "Europe" },
            { country: "Tajikistan", region: "Asia" },
            { country: "Belarus", region: "Europe" },
            { country: "Austria", region: "Europe" },
            { country: "Papua New Guinea", region: "Oceania" },
            { country: "Serbia", region: "Europe" },
            { country: "Israel", region: "Asia" },
            { country: "Switzerland", region: "Europe" },
            { country: "Togo", region: "Africa" },
            { country: "Sierra Leone", region: "Africa" },
            { country: "Laos", region: "Asia" },
            { country: "Paraguay", region: "Latin America" },
            { country: "Bulgaria", region: "Europe" },
            { country: "Libya", region: "Africa" },
            { country: "Lebanon", region: "Asia" },
            { country: "Nicaragua", region: "Latin America" },
            { country: "Kyrgyzstan", region: "Asia" },
            { country: "El Salvador", region: "Latin America" },
            { country: "Turkmenistan", region: "Asia" },
            { country: "Singapore", region: "Asia" },
            { country: "Denmark", region: "Europe" },
            { country: "Finland", region: "Europe" },
            { country: "Congo", region: "Africa" },
            { country: "Slovakia", region: "Europe" },
            { country: "Norway", region: "Europe" },
            { country: "Oman", region: "Asia" },
            { country: "State of Palestine", region: "Asia" },
            { country: "Costa Rica", region: "Latin America" },
            { country: "Liberia", region: "Africa" },
            { country: "Ireland", region: "Europe" },
            { country: "Central African Republic", region: "Africa" },
            { country: "New Zealand", region: "Oceania" },
            { country: "Mauritania", region: "Africa" },
            { country: "Panama", region: "Latin America" },
            { country: "Kuwait", region: "Asia" },
            { country: "Croatia", region: "Europe" },
            { country: "Moldova", region: "Europe" },
            { country: "Georgia", region: "Asia" },
            { country: "Eritrea", region: "Africa" },
            { country: "Uruguay", region: "Latin America" },
            { country: "Bosnia and Herzegovina", region: "Europe" },
            { country: "Mongolia", region: "Asia" },
            { country: "Armenia", region: "Asia" },
            { country: "Jamaica", region: "Latin America" },
            { country: "Qatar", region: "Asia" },
            { country: "Albania", region: "Europe" },
            { country: "Lithuania", region: "Europe" },
            { country: "Namibia", region: "Africa" },
            { country: "Gambia", region: "Africa" },
            { country: "Botswana", region: "Africa" },
            { country: "Gabon", region: "Africa" },
            { country: "Lesotho", region: "Africa" },
            { country: "North Macedonia", region: "Europe" },
            { country: "Slovenia", region: "Europe" },
            { country: "Guinea-Bissau", region: "Africa" },
            { country: "Latvia", region: "Europe" },
            { country: "Bahrain", region: "Asia" },
            { country: "Equatorial Guinea", region: "Africa" },
            { country: "Trinidad and Tobago", region: "Latin America" },
            { country: "Estonia", region: "Europe" },
            { country: "Timor-Leste", region: "Asia" },
            { country: "Mauritius", region: "Africa" },
            { country: "Cyprus", region: "Asia" },
            { country: "Eswatini", region: "Africa" },
            { country: "Djibouti", region: "Africa" },
            { country: "Fiji", region: "Oceania" },
            { country: "Comoros", region: "Africa" },
            { country: "Guyana", region: "Latin America" },
            { country: "Bhutan", region: "Asia" },
            { country: "Solomon Islands", region: "Oceania" },
            { country: "Montenegro", region: "Europe" },
            { country: "Luxembourg", region: "Europe" },
            { country: "Suriname", region: "Latin America" },
            { country: "Cabo Verde", region: "Africa" },
            { country: "Micronesia", region: "Oceania" },
            { country: "Maldives", region: "Asia" },
            { country: "Malta", region: "Europe" },
            { country: "Brunei", region: "Asia" },
            { country: "Belize", region: "Latin America" },
            { country: "Bahamas", region: "Latin America" },
            { country: "Iceland", region: "Europe" },
            { country: "Vanuatu", region: "Oceania" },
            { country: "Barbados", region: "Latin America" },
            { country: "Sao Tome & Principe", region: "Africa" },
            { country: "Samoa", region: "Oceania" },
            { country: "Saint Lucia", region: "Latin America" },
            { country: "Kiribati", region: "Oceania" },
            { country: "Grenada", region: "Latin America" },
            { country: "St. Vincent & Grenadines", region: "Latin America" },
            { country: "Tonga", region: "Oceania" },
            { country: "Seychelles", region: "Africa" },
            { country: "Antigua and Barbuda", region: "Latin America" },
            { country: "Andorra", region: "Europe" },
            { country: "Dominica", region: "Latin America" },
            { country: "Marshall Islands", region: "Oceania" },
            { country: "Saint Kitts & Nevis", region: "Latin America" },
            { country: "Monaco", region: "Europe" },
            { country: "Liechtenstein", region: "Europe" },
            { country: "San Marino", region: "Europe" },
            { country: "Palau", region: "Oceania" },
            { country: "Tuvalu", region: "Oceania" },
            { country: "Nauru", region: "Oceania" },
            { country: "Holy See", region: "Europe" },
        ]
    )
}
