name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push_to_reg:
    name: Build and Push Docker Image to hub
    runs-on: self-hosted

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Build Docker image
      run: sudo docker build . --file Dockerfile --tag nodejs-app:latest
    
    - name: Push Docker Image
      run: sudo docker push nodejs-app:latest
