name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push_to_reg:
    name: Build and Push Docker Image to hub
    runs-on: self-hosted

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Build Docker image
      run: sudo docker build . --file Dockerfile --tag nodejs-app:latest
    
    - name: Tag the Image
      run: sudo docker tag nodejs-app apnavirk/nodejs-app:latest
      
    - name: Push Docker Image to hub
      run: sudo docker push apnavirk/nodejs-app:latest
      
  run_countainer:
    name: run the server
    runs-on: [self-hosted, Linux, X64, ec2]
    needs: build_and_push_to_reg
    
    steps:
      - name: Pull image
        run: sudo docker pull apnavirk/nodejs-app
      
      - name: Run conainer
        run: sudo docker run -d -p 3000:3000 --name nodejs_container apnavirk/nodejs-app:latest
