name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_docker_build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the docker image
        run: sudo docker build . --file Dockerfile --tag nodejs-app:latest    
      - name: Run conainer
        run: sudo docker run -p 3000:3000 nodejs-app:latest &
